### ISSUE TITLE
Whatch later button

### ISSUE THREAD

**Issue by Slamvan** [CodeNinjaUK/youtube-subs-grid#33]
button on no selected video goes to the right side and goes to another video

**Comment by Slamvan** [comment]
![2015-01-12_184233](https://cloud.githubusercontent.com/assets/8472860/5705494/d0d15dd6-9a8a-11e4-9ba8-baa9dd2b1341.png)

**Comment by Bulk70** [comment]
I can't replicate this, but it looks like you're using another extension that's modifying the page (the bar under the video)? Can you try disabling what ever that is and see if that fixes it? If it does let me know the extension name and I'll see if I can work around it.

**Comment by Slamvan** [comment]
Yes, I am sorry that it is not checked it out immediately. (Ratings Preview for YouTube 4.1 ratingspreview.com) causes the conflict.

**Comment by Bulk70** [comment]
No worries, I just checked it out and it looks like actually the bug is with the ratings preview extension - YT rolled out a new version of the subscription page a few days ago which it looks like they haven't updated their extension for. If you disabled my extension you can see the watch later button is still broken. 

I'll keep an eye on it and it its still broken after they update I'll see what I can do. In the mean time you should report this bug to them :)
