### ISSUE TITLE
Automatically Expanding Comments

### ISSUE THREAD

**Issue by mka696** [CodeNinjaUK/youtube-subs-grid#81]
After a lot of testing, I figured out that this extension is causing an issue when I'm on youtube. If I go down to the comment section of a video, and start reading comments, eventually after 5-30 seconds, comments start expanding randomly. It makes it impossible to read comments. I tested it in incognito with no extensions, and just sub grid, and it's definitely what's causing it.

**Comment by DanSmith70** [comment]
I'm going to deploy a bugfix release very shortly (v1.18.1) - once you have it installed can you let me know if this is fixed?

**Comment by mka696** [comment]
For sure. When I get the update I'll let you know. Thanks for jumping on this so quickly, sub grid is one of my fav. extensions.

**Comment by mka696** [comment]
I downloaded the zip from here and loaded it into chrome, and it seems to be fixed for now. If that changes I'll update you.

**Comment by Droyk** [comment]
[**@DanSmith70**](https://github.com/DanSmith70) commented on [Apr 1, 2016, 2:53 AM GMT+5:30](https://github.com/CodeNinjaUK/youtube-subs-grid/issues/81#issuecomment-204135139 "2016-03-31T21:23:56Z - Replied by Github Comment Enhancer"):
> I'm going to deploy a bugfix release very shortly (v1.18.1) - once you have it installed can you let me know if this is fixed?


[**@DanSmith70**](https://github.com/DanSmith70) commented on [Apr 1, 2016, 2:53 AM GMT+5:30](https://github.com/CodeNinjaUK/youtube-subs-grid/issues/81#issuecomment-204135139 "2016-03-31T21:23:56Z - Replied by Github Comment Enhancer"):
> I'm going to deploy a bugfix release very shortly (v1.18.1) - once you have it installed can you let me know if this is fixed?

Actually I am Having this issue too but I really like it because I am too lazy to go to the Comment button and press it to increase more comment .....If you are removing this feature can you plz give the user the choice to auto expand or not

**Comment by mka696** [comment]
Hey Dan, I don't know what happened, but I just noticed that the problem has come back again. Everytime I try to scroll through comments, they start auto expanding.

**Comment by DanSmith70** [comment]
Is this still happening? I've not experienced it my self personally so I'm going to close this but let me know if it's still happening and I'll investigate further.

**Comment by Droyk** [comment]
Well it's not happening to me so I am fine with closing this issue.
